on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      BLENDER_URL: "https://cdn.builder.blender.org/download/daily/archive/blender-4.5.3-candidate+v45.ad3eb9baf0a6-darwin.arm64-release.dmg"
      WHEELS_DIR: wheels

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup GLOMAP build
        run: |
          brew install \
            cmake \
            ninja \
            boost \
            eigen \
            flann \
            freeimage \
            metis \
            glog \
            googletest \
            ceres-solver \
            qt@5 \
            glew \
            cgal \
            sqlite3 \
            ccache
        
      - name: Clone and build GLOMAP
        run: |
          cd ..
          git clone --branch 4f475de4813f572926980bd2a433b44f05a95bcf https://github.com/colmap/glomap/ glomap
          cd glomap
          cmake --version
          mkdir build
          cd build
          cmake .. \
            -GNinja \
            -DCMAKE_BUILD_TYPE=Release \
            -DTESTS_ENABLED=ON \
            -DCMAKE_PREFIX_PATH="$(brew --prefix qt@5)"
          ninja
          cp glomap/glomap ../../glomap-blender/glomap_subprocess

      - name: Download Blender
        run: |
          curl -L "$BLENDER_URL" -o blender.dmg
          hdiutil attach blender.dmg -nobrowse -quiet
          VOL=$(ls /Volumes | grep -i Blender | head -n1)
          echo "Mounted at /Volumes/$VOL"

          mkdir blender
          cp -R "/Volumes/$VOL/Blender.app" blender/
          hdiutil detach "/Volumes/$VOL" -quiet

      - name: Download Python wheels
        run: |
          mkdir -p ${WHEELS_DIR}
          blender/Blender.app/Contents/Resources/4.5/python/bin/python3.11 -m pip download --dest ${WHEELS_DIR} -r requirements.txt --only-binary=:all: --python-version=3.11 --platform=macosx_14_0_arm64
          blender/Blender.app/Contents/Resources/4.5/python/bin/python3.11 -m pip download --dest ${WHEELS_DIR} -r requirements.txt --only-binary=:all: --python-version=3.11 --platform=manylinux_2_28_x86_64
          blender/Blender.app/Contents/Resources/4.5/python/bin/python3.11 -m pip download --dest ${WHEELS_DIR} -r requirements.txt --only-binary=:all: --python-version=3.11 --platform=win_amd64

      - name: Build extension
        run: |
          mkdir -p dist
          blender/Blender.app/Contents/MacOS/Blender --command extension build --split-platforms --output-dir dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: blender-extension
          path: dist/